name: haskell-medallion
version: "0.1.0"
dependencies:
  - base >= 4.14 && < 5
  - cassava
  - vector
  - text
  - containers
  - Chart
  - Chart-cairo

executables:
  haskell-medallion:
    main: Main.hs
    source-dirs: src
