name: haskell-data-project
version: "0.1.0"
build-type: Simple

dependencies:
  - base >= 4.7 && < 5
  - cassava
  - vector
  - containers
  - text

executables:
  haskell-data-project:
    source-dirs: src
    main: Main.hs
